# Generated by Django 3.1.4 on 2021-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
